[package]
name = "orao-aptos-vrf"
version = "0.1.0"
edition = "2021"
authors = ["ORAO Devs <hello@orao.network>"]
homepage = "https://orao.network"
repository = "https://github.com/orao-network/vrf-aptos"
license = "Apache-2.0"
keywords = ["aptos", "vrf", "ed25519"]
description = "ORAO Verifiable Random Function for Aptos."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
aptos-sdk = { git = "https://github.com/aptos-labs/aptos-core", branch = "devnet" }
hex = "0.4.3"
url = "2.3.1"
serde = "1.0.147"
